### ISSUE TITLE
Example does not match API documentation for timestamp

### ISSUE THREAD

**Issue by JLademan** [coinbase-samples/prime-scripts-py#13]
In the documentation:

> timestamp: [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp for your request (seconds since the epoch). Valid format: %Y-%M-%DT%H:%M:%SZ, for example, 2022-02-19T20:05:22Z

from the example:

> timestamp = str(int(time.time()))

It appears that the actual working timestamp is the example timestamp (which is not ISO 8601)

**Comment by jc-cb** [comment]
@JLademan thanks for this. ISO 8601 is indeed supported. You can test with the following code: 

s = time.gmtime(time.time())
timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", s)

I do agree that the more simple solution is the example. I will request to have the docs updated with added optionality.
