### ISSUE TITLE
New API format

### ISSUE THREAD

**Issue by Ju-creator-beep** [coinbase-samples/prime-scripts-py#27]
New API format provide by coinbase do not respect this :
API_KEY = os.environ.get('ACCESS_KEY')
SECRET_KEY = os.environ.get('SIGNING_KEY')
PASSPHRASE = os.environ.get('PASSPHRASE')
PORTFOLIO_ID = os.environ.get('PORTFOLIO_ID')

What can I do to reuse past algorithms?
Best

**Comment by jc-cb** [comment]
This will still work. Can you please provide an example of where you are encountering such an issue?
